#!/bin/bash
awk '
/private val _lastSyncFormatted = MutableStateFlow/ {
    print "    // --- Device Management ---"
    print "    private val _isDeviceBlocked = MutableStateFlow(false)"
    print "    val isDeviceBlocked: StateFlow<Boolean> = _isDeviceBlocked.asStateFlow()"
    print "    private var heartbeatJob: Job? = null"
    print "    private var deviceId: String? = null"
    print ""
    print "    fun initDeviceManager(prefs: android.content.SharedPreferences) {"
    print "        var id = prefs.getString(\"playfilme_device_id\", null)"
    print "        if (id == null) {"
    print "            id = UUID.randomUUID().toString()"
    print "            prefs.edit().putString(\"playfilme_device_id\", id).apply()"
    print "        }"
    print "        deviceId = id"
    print ""
    print "        val db = firestore ?: return"
    print "        db.collection(\"devices\").document(id).addSnapshotListener { snapshot, _ ->"
    print "            if (snapshot != null && snapshot.exists()) {"
    print "                val blocked = snapshot.getBoolean(\"isBlocked\") ?: false"
    print "                _isDeviceBlocked.value = blocked"
    print "            }"
    print "        }"
    print ""
    print "        heartbeatJob?.cancel()"
    print "        heartbeatJob = serviceScope.launch {"
    print "            while(true) {"
    print "                try {"
    print "                    val deviceMap = hashMapOf<String, Any>("
    print "                        \"deviceId\" to id,"
    print "                        \"name\" to getDeviceInfo(),"
    print "                        \"platform\" to \"Android\","
    print "                        \"appVersion\" to getBrowserInfo(),"
    print "                        \"lastActivity\" to System.currentTimeMillis()"
    print "                    )"
    print "                    val docRef = db.collection(\"devices\").document(id)"
    print "                    val snap = docRef.get().await()"
    print "                    if (!snap.exists()) {"
    print "                        deviceMap[\"firstConnection\"] = System.currentTimeMillis()"
    print "                        deviceMap[\"isBlocked\"] = false"
    print "                    }"
    print "                    docRef.set(deviceMap, SetOptions.merge()).await()"
    print "                } catch (e: Exception) {"
    print "                    Log.e(TAG, \"Failed to send heartbeat: ${e.message}\")"
    print "                }"
    print "                delay(3 * 60 * 1000L) // 3 minutos"
    print "            }"
    print "        }"
    print "    }"
    print ""
}
{print}
' app/src/main/java/com/example/data/remote/FirebaseService.kt > temp_firebase.kt && mv temp_firebase.kt app/src/main/java/com/example/data/remote/FirebaseService.kt
